import csv
import json
import os

# Base directory
output_dir = r"u:\Internship\Troopod"

raw_rows = [
    {
        "handle": "purelane-tap-cleaner-limescale-remover",
        "title": "Tap Cleaner & Limescale Remover",
        "body": "<p>Melts away hard water stains and limescale on taps and fittings.</p>",
        "type": "Product",
        "tags": "cleaner,bathroom,bestseller",
        "sku": "PUR-TAP-500",
        "grams": 500,
        "qty": 150,
        "price": 200.0,
        "compare": 299.0,
        "img": "placeholder.jpg",
        "alt": "Tap cleaner and limescale remover bottle",
        "seo_title": "Tap Cleaner & Limescale Remover",
        "seo_desc": "Melts hard water stains and limescale.",
        "badge": "Best seller",
        "rating": 4.8,
        "reviews": 237,
        "components": [],
        "component_labels": [],
        "bundle_size": "",
        "features": []
    },
    {
        "handle": "purelane-kitchen-cleaner-foaming",
        "title": "Kitchen Cleaner, Foaming",
        "body": "<p>Cuts through grease instantly with a foaming, plant-based formula.</p>",
        "type": "Product",
        "tags": "cleaner,kitchen,bestseller",
        "sku": "PUR-KIT-500",
        "grams": 500,
        "qty": 140,
        "price": 200.0,
        "compare": 299.0,
        "img": "placeholder.jpg",
        "alt": "Foaming kitchen cleaner spray",
        "seo_title": "Kitchen Cleaner, Foaming",
        "seo_desc": "Foaming plant-based kitchen cleaner.",
        "badge": "Best seller",
        "rating": 4.8,
        "reviews": 254,
        "components": [],
        "component_labels": [],
        "bundle_size": "",
        "features": []
    },
    {
        "handle": "purelane-copper-bronze-brass-cleaner",
        "title": "Copper, Bronze & Brass Cleaner",
        "body": "<p>Restores shine to copper, bronze and brass without harsh chemicals.</p>",
        "type": "Product",
        "tags": "cleaner,metal,top-rated",
        "sku": "PUR-CBB-300",
        "grams": 300,
        "qty": 0,
        "price": 200.0,
        "compare": 299.0,
        "img": "placeholder.jpg",
        "alt": "Copper bronze and brass cleaner pump bottle",
        "seo_title": "Copper, Bronze & Brass Cleaner",
        "seo_desc": "Plant-based metal cleaner and polish.",
        "badge": "Top rated",
        "rating": 4.8,
        "reviews": 231,
        "components": [],
        "component_labels": [],
        "bundle_size": "",
        "features": []
    },
    {
        "handle": "purelane-washing-machine-cleaner-descaler",
        "title": "Washing Machine Cleaner & Descaler",
        "body": "<p>8 tablets that deep-clean and descale your washing machine drum.</p>",
        "type": "Product",
        "tags": "cleaner,laundry,new",
        "sku": "PUR-WMD-008",
        "grams": 200,
        "qty": 90,
        "price": 200.0,
        "compare": 299.0,
        "img": "",
        "alt": "",
        "seo_title": "Washing Machine Cleaner & Descaler",
        "seo_desc": "Washing machine cleaner and descaler tablets.",
        "badge": "New",
        "rating": 4.8,
        "reviews": 183,
        "components": [],
        "component_labels": [],
        "bundle_size": "",
        "features": []
    },
    {
        "handle": "purelane-dishwash-gel-organic",
        "title": "Dishwash Gel, Organic",
        "body": "<p>An organic dishwash gel that cuts grease and leaves dishes squeaky clean.</p>",
        "type": "Product",
        "tags": "cleaner,dishwash",
        "sku": "PUR-DSH-750",
        "grams": 750,
        "qty": 110,
        "price": 200.0,
        "compare": 299.0,
        "img": "placeholder.jpg",
        "alt": "Organic dishwash liquid gel bottle",
        "seo_title": "Dishwash Gel, Organic",
        "seo_desc": "Organic dishwash gel for grease-free dishes.",
        "badge": "",
        "rating": 4.6,
        "reviews": 96,
        "components": [],
        "component_labels": [],
        "bundle_size": "",
        "features": []
    },
    {
        "handle": "purelane-floor-cleaner-herbal",
        "title": "Floor Cleaner, Natural Herbal",
        "body": "<p>A natural herbal floor cleaner that kills 99.9% of germs, safe on tiles and wood.</p>",
        "type": "Product",
        "tags": "cleaner,floor,herbal",
        "sku": "PUR-FLR-1000",
        "grams": 1000,
        "qty": 100,
        "price": 200.0,
        "compare": 299.0,
        "img": "placeholder.jpg",
        "alt": "Natural herbal floor cleaner bottle",
        "seo_title": "Floor Cleaner, Natural Herbal",
        "seo_desc": "Herbal floor cleaner that kills 99.9 percent of germs.",
        "badge": "",
        "rating": 4.5,
        "reviews": 88,
        "components": [],
        "component_labels": [],
        "bundle_size": "",
        "features": []
    },
    {
        "handle": "purelane-toilet-cleaner-non-toxic",
        "title": "Toilet Cleaner, Non-Toxic",
        "body": "<p>A non-toxic toilet cleaner that fights limescale and kills 99.9% of germs.</p>",
        "type": "Product",
        "tags": "cleaner,toilet,bathroom",
        "sku": "PUR-TLT-500",
        "grams": 500,
        "qty": 120,
        "price": 200.0,
        "compare": 299.0,
        "img": "placeholder.jpg",
        "alt": "Non-toxic toilet cleaner bottle",
        "seo_title": "Toilet Cleaner, Non-Toxic",
        "seo_desc": "Non-toxic toilet cleaner that fights limescale.",
        "badge": "",
        "rating": 4.5,
        "reviews": 74,
        "components": [],
        "component_labels": [],
        "bundle_size": "",
        "features": []
    },
    {
        "handle": "purelane-handwash-gentle-hydrating",
        "title": "Handwash, Gentle Hydrating Liquid",
        "body": "<p>A gentle hydrating liquid handwash for everyday use.</p>",
        "type": "Product",
        "tags": "handwash,skin",
        "sku": "PUR-HND-300",
        "grams": 300,
        "qty": 130,
        "price": 166.0,
        "compare": 249.0,
        "img": "placeholder.jpg",
        "alt": "Gentle hydrating liquid handwash bottle",
        "seo_title": "Handwash, Gentle Hydrating Liquid",
        "seo_desc": "Gentle hydrating handwash for daily use.",
        "badge": "",
        "rating": 4.4,
        "reviews": 61,
        "components": [],
        "component_labels": [],
        "bundle_size": "",
        "features": []
    },
    {
        "handle": "purelane-laundry-detergent-non-toxic",
        "title": "Laundry Detergent, Non-Toxic",
        "body": "<p>Removes tough stains and odour without harsh chemicals.</p>",
        "type": "Product",
        "tags": "laundry,detergent",
        "sku": "PUR-LDT-1000",
        "grams": 1000,
        "qty": 95,
        "price": 233.0,
        "compare": 349.0,
        "img": "placeholder.jpg",
        "alt": "Non-toxic laundry detergent pack",
        "seo_title": "Laundry Detergent, Non-Toxic",
        "seo_desc": "Non-toxic laundry detergent for tough stains.",
        "badge": "",
        "rating": 4.5,
        "reviews": 52,
        "components": [],
        "component_labels": [],
        "bundle_size": "",
        "features": []
    },
    {
        "handle": "purelane-fabric-conditioner",
        "title": "Fabric Conditioner",
        "body": "<p>Softens and freshens every wash.</p>",
        "type": "Product",
        "tags": "laundry,fabric-care",
        "sku": "PUR-FBC-1000",
        "grams": 1000,
        "qty": 85,
        "price": 200.0,
        "compare": 299.0,
        "img": "placeholder.jpg",
        "alt": "Fabric conditioner bottle",
        "seo_title": "Fabric Conditioner",
        "seo_desc": "Softens and freshens every wash.",
        "badge": "",
        "rating": 4.3,
        "reviews": 39,
        "components": [],
        "component_labels": [],
        "bundle_size": "",
        "features": []
    },
    {
        "handle": "purelane-machine-cleaner-powder",
        "title": "Machine Cleaner Powder",
        "body": "<p>Deep-cleans your washing machine drum and removes buildup.</p>",
        "type": "Product",
        "tags": "laundry,machine-care",
        "sku": "PUR-MCP-250",
        "grams": 250,
        "qty": 70,
        "price": 200.0,
        "compare": 299.0,
        "img": "placeholder.jpg",
        "alt": "Machine cleaner powder pack",
        "seo_title": "Machine Cleaner Powder",
        "seo_desc": "Deep-cleans washing machine drum.",
        "badge": "",
        "rating": 4.2,
        "reviews": 28,
        "components": [],
        "component_labels": [],
        "bundle_size": "",
        "features": []
    },
    {
        "handle": "purelane-magic-eraser",
        "title": "Magic Eraser",
        "body": "<p>Scrubs away soap scum and stains without scratching surfaces.</p>",
        "type": "Product",
        "tags": "bathroom,scrub",
        "sku": "PUR-ERS-003",
        "grams": 150,
        "qty": 105,
        "price": 200.0,
        "compare": 299.0,
        "img": "placeholder.jpg",
        "alt": "Purelane magic eraser pack",
        "seo_title": "Magic Eraser",
        "seo_desc": "Magic eraser for scrubbing soap scum.",
        "badge": "",
        "rating": 4.4,
        "reviews": 45,
        "components": [],
        "component_labels": [],
        "bundle_size": "",
        "features": []
    },
    {
        "handle": "purelane-complete-home-deep-cleaning-ritual-kit-with-reusable-bottles",
        "title": "Purelane Complete Home Deep-Cleaning Ritual Kit With Reusable Spray Bottles And Cotton Cloths",
        "body": "<p>A full home deep-cleaning ritual kit including reusable spray bottles and cotton cloths.</p>",
        "type": "Product",
        "tags": "cleaner,kit,long-title-test",
        "sku": "PUR-KIT-DEEP-001",
        "grams": 1500,
        "qty": 30,
        "price": 899.0,
        "compare": 999.0,
        "img": "placeholder.jpg",
        "alt": "Purelane deep-cleaning ritual kit",
        "seo_title": "Purelane Complete Home Deep-Cleaning Ritual Kit",
        "seo_desc": "Full home deep-cleaning ritual kit with reusable accessories.",
        "badge": "",
        "rating": 4.7,
        "reviews": 41,
        "components": [],
        "component_labels": [],
        "bundle_size": "",
        "features": []
    },
    {
        "handle": "purelane-combo-kitchen-essentials",
        "title": "Kitchen essentials",
        "body": "<p>Includes: Foaming Kitchen Cleaner, Dishwash Gel &amp; Tap Cleaner. Everything for a sparkling kitchen, no need to pick separately.</p>",
        "type": "Combo",
        "tags": "combo,kitchen,most-popular",
        "sku": "PUR-CMB-KIT",
        "grams": 1250,
        "qty": 60,
        "price": 499.0,
        "compare": 897.0,
        "img": "placeholder.jpg",
        "alt": "Kitchen essentials combo pack",
        "seo_title": "Kitchen essentials combo",
        "seo_desc": "Kitchen cleaner, dishwash gel and tap cleaner combo.",
        "badge": "Most popular",
        "rating": 4.7,
        "reviews": 64,
        "components": [
            "purelane-kitchen-cleaner-foaming",
            "purelane-dishwash-gel-organic",
            "purelane-tap-cleaner-limescale-remover"
        ],
        "component_labels": [
            "Foaming Kitchen Cleaner",
            "Dishwash Gel",
            "Tap Cleaner"
        ],
        "bundle_size": "",
        "features": []
    },
    {
        "handle": "purelane-combo-laundry-care-bundle",
        "title": "Laundry care bundle",
        "body": "<p>Includes: Laundry Detergent, Fabric Conditioner &amp; Machine Cleaner Powder. Softer, fresher wash, all in one box.</p>",
        "type": "Combo",
        "tags": "combo,laundry",
        "sku": "PUR-CMB-LDY",
        "grams": 1350,
        "qty": 50,
        "price": 499.0,
        "compare": 947.0,
        "img": "placeholder.jpg",
        "alt": "Laundry care bundle pack",
        "seo_title": "Laundry care bundle",
        "seo_desc": "Laundry detergent, fabric conditioner and machine cleaner powder combo.",
        "badge": "",
        "rating": 4.5,
        "reviews": 37,
        "components": [
            "purelane-laundry-detergent-non-toxic",
            "purelane-fabric-conditioner",
            "purelane-machine-cleaner-powder"
        ],
        "component_labels": [
            "Laundry Detergent",
            "Fabric Conditioner",
            "Machine Cleaner Powder"
        ],
        "bundle_size": "",
        "features": []
    },
    {
        "handle": "purelane-combo-complete-home-bundle",
        "title": "Complete home bundle",
        "body": "<p>Includes: Kitchen Cleaner, Laundry Detergent, Floor Cleaner, Toilet Cleaner &amp; Handwash. Our biggest saving box.</p>",
        "type": "Combo",
        "tags": "combo,whole-home,best-value",
        "sku": "PUR-CMB-CPL",
        "grams": 2200,
        "qty": 35,
        "price": 799.0,
        "compare": 1495.0,
        "img": "placeholder.jpg",
        "alt": "Complete home bundle pack",
        "seo_title": "Complete home bundle",
        "seo_desc": "Kitchen, laundry, floor, toilet and handwash combo.",
        "badge": "Best value",
        "rating": 4.6,
        "reviews": 52,
        "components": [
            "purelane-kitchen-cleaner-foaming",
            "purelane-laundry-detergent-non-toxic",
            "purelane-floor-cleaner-herbal",
            "purelane-toilet-cleaner-non-toxic",
            "purelane-handwash-gentle-hydrating"
        ],
        "component_labels": [
            "Kitchen Cleaner",
            "Laundry Detergent",
            "Floor Cleaner",
            "Toilet Cleaner",
            "Handwash"
        ],
        "bundle_size": "",
        "features": []
    },
    {
        "handle": "purelane-combo-bathroom-deep-clean",
        "title": "Bathroom deep clean",
        "body": "<p>Includes: Toilet Cleaner, Tap Cleaner &amp; Magic Eraser. A complete bathroom refresh in one box.</p>",
        "type": "Combo",
        "tags": "combo,bathroom",
        "sku": "PUR-CMB-BTH",
        "grams": 1200,
        "qty": 55,
        "price": 499.0,
        "compare": 897.0,
        "img": "placeholder.jpg",
        "alt": "Bathroom deep clean combo pack",
        "seo_title": "Bathroom deep clean",
        "seo_desc": "Toilet cleaner, tap cleaner and magic eraser combo.",
        "badge": "",
        "rating": 4.4,
        "reviews": 33,
        "components": [
            "purelane-toilet-cleaner-non-toxic",
            "purelane-tap-cleaner-limescale-remover",
            "purelane-magic-eraser"
        ],
        "component_labels": [
            "Toilet Cleaner",
            "Tap Cleaner",
            "Magic Eraser"
        ],
        "bundle_size": "",
        "features": []
    },
    {
        "handle": "purelane-combo-hard-water-solution-kit",
        "title": "Hard water solution kit",
        "body": "<p>Includes: Tap Cleaner &amp; Toilet Cleaner. A quick, focused fix for hard water stains across the home.</p>",
        "type": "Combo",
        "tags": "combo,hard-water",
        "sku": "PUR-CMB-HWS",
        "grams": 900,
        "qty": 65,
        "price": 349.0,
        "compare": 598.0,
        "img": "placeholder.jpg",
        "alt": "Hard water solution kit pack",
        "seo_title": "Hard water solution kit",
        "seo_desc": "Tap cleaner and toilet cleaner combo for hard water.",
        "badge": "",
        "rating": 4.3,
        "reviews": 21,
        "components": [
            "purelane-tap-cleaner-limescale-remover",
            "purelane-toilet-cleaner-non-toxic"
        ],
        "component_labels": [
            "Tap Cleaner",
            "Toilet Cleaner"
        ],
        "bundle_size": "",
        "features": []
    },
    {
        "handle": "purelane-bundle-starter",
        "title": "Starter bundle",
        "body": "<p>Pick any two products. Free shipping across India.</p>",
        "type": "Bundle",
        "tags": "bundle,tier,starter",
        "sku": "PUR-BND-STR",
        "grams": 900,
        "qty": 45,
        "price": 349.0,
        "compare": 598.0,
        "img": "placeholder.jpg",
        "alt": "Starter bundle box",
        "seo_title": "Starter bundle",
        "seo_desc": "Two-product starter bundle, flat price.",
        "badge": "",
        "rating": "",
        "reviews": "",
        "components": [],
        "component_labels": [],
        "bundle_size": 2,
        "features": [
            "Pick any two products",
            "Free shipping across India"
        ]
    },
    {
        "handle": "purelane-bundle-most-popular",
        "title": "Most popular bundle",
        "body": "<p>Pick any three products. Covers kitchen and laundry. Free shipping across India.</p>",
        "type": "Bundle",
        "tags": "bundle,tier,most-popular",
        "sku": "PUR-BND-POP",
        "grams": 1350,
        "qty": 40,
        "price": 499.0,
        "compare": 897.0,
        "img": "placeholder.jpg",
        "alt": "Most popular bundle box",
        "seo_title": "Most popular bundle",
        "seo_desc": "Three-product bundle covering kitchen and laundry.",
        "badge": "Most popular",
        "rating": "",
        "reviews": "",
        "components": [],
        "component_labels": [],
        "bundle_size": 3,
        "features": [
            "Pick any three products",
            "Covers kitchen and laundry",
            "Free shipping across India"
        ]
    },
    {
        "handle": "purelane-bundle-whole-home",
        "title": "Whole home bundle",
        "body": "<p>Pick any five products. Every room in one order. Free shipping across India.</p>",
        "type": "Bundle",
        "tags": "bundle,tier,whole-home",
        "sku": "PUR-BND-WHL",
        "grams": 2200,
        "qty": 20,
        "price": 799.0,
        "compare": 1495.0,
        "img": "placeholder.jpg",
        "alt": "Whole home bundle box",
        "seo_title": "Whole home bundle",
        "seo_desc": "Five-product bundle covering every room.",
        "badge": "",
        "rating": "",
        "reviews": "",
        "components": [],
        "component_labels": [],
        "bundle_size": 5,
        "features": [
            "Pick any five products",
            "Every room in one order",
            "Free shipping across India"
        ]
    }
]

# 1. GENERATE PURELANE-PRODUCTS-IMPORT-V2.CSV (Exact Claude output with pipe delimiters)
fields_v2 = [
    "Handle","Title","Body (HTML)","Vendor","Product Category","Type","Tags","Published",
    "Option1 Name","Option1 Value","Variant SKU","Variant Grams","Variant Inventory Tracker",
    "Variant Inventory Qty","Variant Inventory Policy","Variant Fulfillment Service","Variant Price",
    "Variant Compare At Price","Variant Requires Shipping","Variant Taxable","Image Src","Image Position",
    "Image Alt Text","Gift Card","SEO Title","SEO Description","Status",
    "Metafield: purelane.badge [single_line_text_field]",
    "Metafield: purelane.rating [number_decimal]",
    "Metafield: purelane.review_count [number_integer]",
    "Metafield: purelane.components [list.product_reference]",
    "Metafield: purelane.component_labels [list.single_line_text_field]",
    "Metafield: purelane.bundle_size [number_integer]",
    "Metafield: purelane.features [list.single_line_text_field]"
]

v2_path = os.path.join(output_dir, "purelane-products-import-v2.csv")
with open(v2_path, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fields_v2)
    writer.writeheader()
    for r in raw_rows:
        writer.writerow({
            "Handle": r["handle"],
            "Title": r["title"],
            "Body (HTML)": r["body"],
            "Vendor": "Purelane",
            "Product Category": r["type"],
            "Type": r["type"],
            "Tags": r["tags"],
            "Published": "TRUE",
            "Option1 Name": "Size",
            "Option1 Value": "Default",
            "Variant SKU": r["sku"],
            "Variant Grams": r["grams"],
            "Variant Inventory Tracker": "shopify",
            "Variant Inventory Qty": r["qty"],
            "Variant Inventory Policy": "deny",
            "Variant Fulfillment Service": "manual",
            "Variant Price": r["price"],
            "Variant Compare At Price": r["compare"],
            "Variant Requires Shipping": "TRUE",
            "Variant Taxable": "TRUE",
            "Image Src": r["img"],
            "Image Position": "1" if r["img"] else "",
            "Image Alt Text": r["alt"] if r["img"] else "",
            "Gift Card": "FALSE",
            "SEO Title": r["seo_title"],
            "SEO Description": r["seo_desc"],
            "Status": "active",
            "Metafield: purelane.badge [single_line_text_field]": r["badge"],
            "Metafield: purelane.rating [number_decimal]": r["rating"],
            "Metafield: purelane.review_count [number_integer]": r["reviews"],
            "Metafield: purelane.components [list.product_reference]": "|".join(r["components"]),
            "Metafield: purelane.component_labels [list.single_line_text_field]": "|".join(r["component_labels"]),
            "Metafield: purelane.bundle_size [number_integer]": r["bundle_size"],
            "Metafield: purelane.features [list.single_line_text_field]": "|".join(r["features"]),
        })

print("Generated:", v2_path)

# 2. GENERATE PURELANE-PRODUCTS-SHOPIFY-NATIVE.CSV
# Optimized for standard Shopify Admin -> Products -> Import
# Headers formatted as: product.metafields.namespace.key
# Delimiter for list product references is semicolon (;)
# List of single line text formatted as JSON list (or semicolon)
# Image Src is left blank so Shopify doesn't fail trying to download local placeholder.jpg
fields_native = [
    "Handle","Title","Body (HTML)","Vendor","Product Category","Type","Tags","Published",
    "Option1 Name","Option1 Value","Variant SKU","Variant Grams","Variant Inventory Tracker",
    "Variant Inventory Qty","Variant Inventory Policy","Variant Fulfillment Service","Variant Price",
    "Variant Compare At Price","Variant Requires Shipping","Variant Taxable","Image Src","Image Position",
    "Image Alt Text","Gift Card","SEO Title","SEO Description","Status",
    "product.metafields.purelane.badge",
    "product.metafields.purelane.rating",
    "product.metafields.purelane.review_count",
    "product.metafields.purelane.components",
    "product.metafields.purelane.component_labels",
    "product.metafields.purelane.bundle_size",
    "product.metafields.purelane.features"
]

native_path = os.path.join(output_dir, "purelane-products-shopify-native.csv")
with open(native_path, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fields_native)
    writer.writeheader()
    for r in raw_rows:
        comp_str = ";".join(r["components"])
        comp_labels_str = json.dumps(r["component_labels"]) if r["component_labels"] else ""
        features_str = json.dumps(r["features"]) if r["features"] else ""

        writer.writerow({
            "Handle": r["handle"],
            "Title": r["title"],
            "Body (HTML)": r["body"],
            "Vendor": "Purelane",
            "Product Category": r["type"],
            "Type": r["type"],
            "Tags": r["tags"],
            "Published": "TRUE",
            "Option1 Name": "Size",
            "Option1 Value": "Default",
            "Variant SKU": r["sku"],
            "Variant Grams": r["grams"],
            "Variant Inventory Tracker": "shopify",
            "Variant Inventory Qty": r["qty"],
            "Variant Inventory Policy": "deny",
            "Variant Fulfillment Service": "manual",
            "Variant Price": r["price"],
            "Variant Compare At Price": r["compare"],
            "Variant Requires Shipping": "TRUE",
            "Variant Taxable": "TRUE",
            "Image Src": "",  # Blank prevents Shopify 404 / download failure
            "Image Position": "",
            "Image Alt Text": "",
            "Gift Card": "FALSE",
            "SEO Title": r["seo_title"],
            "SEO Description": r["seo_desc"],
            "Status": "active",
            "product.metafields.purelane.badge": r["badge"],
            "product.metafields.purelane.rating": r["rating"],
            "product.metafields.purelane.review_count": r["reviews"],
            "product.metafields.purelane.components": comp_str,
            "product.metafields.purelane.component_labels": comp_labels_str,
            "product.metafields.purelane.bundle_size": r["bundle_size"],
            "product.metafields.purelane.features": features_str,
        })

print("Generated:", native_path)
